name: CD-Liara
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_CONNECTION: ${{ secrets.DATABASE_CONNECTION }}
        run: |
          npm i -g @liara/cli@3
          liara env set JWT_SECRET="$JWT_SECRET" DATABASE_CONNECTION="$DATABASE_CONNECTION" --app="negar" --api-token="$LIARA_TOKEN" --force
          liara deploy --app="negar" --api-token="$LIARA_TOKEN" --detach --port=3000
